"""ReportWriterTool — structured Markdown report assembly from Quant output."""

from __future__ import annotations

import logging
from typing import Any

from langchain_core.prompts import ChatPromptTemplate
from langchain_core.tools import tool
from pydantic import Field

from ..core.llm import content_to_str
from .base import StrictToolInput, safe_tool_call

logger = logging.getLogger(__name__)

_REPORT_PROMPT = ChatPromptTemplate.from_messages(
    [
        (
            "system",
            """You are a senior financial analyst editor. Your task is to produce a
structured Markdown report from the quantitative analysis provided.

MANDATORY SECTIONS — every report MUST include all of the following:
1. # Executive Summary
2. ## Data Coverage Summary  (tickers analysed ✓, data gaps ✗, errors encountered)
3. ## Financial Overview
4. ## Quantitative Analysis  (CAGR, ratios, peer comparison, sector benchmark)
5. ## Bull Case
6. ## Bear Case
7. ## Conclusion
8. ---
   *DISCLAIMER: This report was generated by an AI system. All figures should be
   independently verified before making any investment decisions. This is not
   financial advice.*

Rules:
- Use ONLY numbers that appear in the analysis JSON. Do NOT invent figures.
- Format all numbers in a professional, human-readable style: e.g. $4.17T (not 4173852573696), $285.5B (not 285508000000.0), 27.2% (not 0.27152002), 34.4x P/E (not 34.362755). Round to 3 significant figures.
- Every quantitative claim MUST cite its source tool in parentheses, e.g. "(Source: fundamentals)" or "(Source: benchmark_lookup)".
- Do NOT add [UNVERIFIED] tags — grounding is handled in post-processing.
- Keep language professional, concise, and analytical.""",
        ),
        (
            "human",
            "Analysis JSON:\n\n{analysis_json}\n\nProduce the full Markdown report now.",
        ),
    ]
)

# Module-level primary LLM; injected at startup via configure().
_primary_llm = None


def configure(primary_llm) -> None:
    global _primary_llm
    _primary_llm = primary_llm


class ReportWriterInput(StrictToolInput):
    analysis_json: str = Field(
        description="JSON string of the QuantAnalyst output to convert into a report"
    )
    tickers: list[str] = Field(description="List of tickers analysed")
    data_gaps: list[str] = Field(
        default_factory=list,
        description="List of data gaps identified during research",
    )


@tool("report_writer", args_schema=ReportWriterInput)
def report_writer_tool(
    analysis_json: str, tickers: list[str], data_gaps: list[str]
) -> str:
    """Assemble the final Markdown report from quantitative analysis JSON.

    Enforces mandatory SOP sections and appends the disclaimer footer.
    """
    def _run():
        if _primary_llm is None:
            raise RuntimeError(
                "ReportWriterTool not configured — call report_writer.configure(llm)"
            )
        chain = _REPORT_PROMPT | _primary_llm
        response = chain.invoke({"analysis_json": analysis_json})
        raw_content = response.content if hasattr(response, "content") else response
        report = content_to_str(raw_content)
        return _enforce_disclaimer(report)

    return safe_tool_call(
        "report_writer",
        _run,
        {"analysis_json": analysis_json[:200], "tickers": tickers},
    )


_DISCLAIMER = (
    "\n\n---\n"
    "*DISCLAIMER: This report was generated by an AI system. "
    "All figures should be independently verified before making any investment "
    "decisions. This is not financial advice.*"
)


def _enforce_disclaimer(report: str) -> str:
    """Guarantee the disclaimer footer is present regardless of LLM output."""
    if "This is not financial advice" not in report:
        return report + _DISCLAIMER
    return report
