"""ReportWriterTool — structured Markdown report assembly from Quant output.

Two-call strategy:
  Call 1 (Flash-Lite / subllm): Executive Summary, Data Coverage, Financial Overview
  Call 2 (primary Flash): Quantitative Analysis, Bull Case, Bear Case, Conclusion

This keeps the lightweight structural sections cheap (Flash-Lite) while
the analytical sections use full reasoning capacity (Flash). A post-generation
section validator ensures all mandatory sections are present.
"""

from __future__ import annotations

import logging

from langchain_core.messages import SystemMessage, HumanMessage
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.tools import tool
from pydantic import Field

from ..core.llm import content_to_str
from .base import StrictToolInput, safe_tool_call

logger = logging.getLogger(__name__)

# Sections 1–3: structural / coverage — generated by Flash-Lite
_STRUCTURAL_SYSTEM = """You are a senior financial analyst editor.
Generate ONLY these three Markdown sections from the analysis JSON provided:

1. # Executive Summary  (2-3 sentences: key finding, overall recommendation)
2. ## Data Coverage Summary  (table: ticker ✓/✗ for each data type; list any data gaps)
3. ## Financial Overview  (current price, market cap, PE ratio, sector — one paragraph)

Rules:
- Use ONLY numbers that appear in the analysis JSON. Do NOT invent figures.
- Format numbers professionally: $4.17T, 27.2%, 34.4x P/E. Round to 3 significant figures.
- Every quantitative claim MUST cite source: (Source: fundamentals), (Source: price_history).
- Output ONLY the three sections above — no other text."""

# Sections 4–7: analytical — generated by primary Flash
_ANALYTICAL_SYSTEM = """You are a senior financial analyst editor.
Generate ONLY these four Markdown sections from the analysis JSON provided:

4. ## Quantitative Analysis  (CAGR, Sharpe ratio, P/E vs sector, FCF yield, peer comparison)
5. ## Bull Case  (bullet list of 2-3 specific data-driven reasons to be optimistic)
6. ## Bear Case  (bullet list of 2-3 concrete risks with cited figures)
7. ## Conclusion  (final investment perspective, 2-3 sentences)

Rules:
- Use ONLY numbers that appear in the analysis JSON. Do NOT invent figures.
- Format numbers professionally: $4.17T, 27.2%, 34.4x P/E. Round to 3 significant figures.
- Every quantitative claim MUST cite source: (Source: price_metrics), (Source: benchmark_lookup).
- Do NOT add [UNVERIFIED] tags — grounding is handled in post-processing.
- Output ONLY the four sections above — no other text."""

# Required section headings for post-generation validation
_REQUIRED_SECTIONS = [
    "Executive Summary",
    "Data Coverage",
    "Financial Overview",
    "Quantitative Analysis",
    "Bull Case",
    "Bear Case",
    "Conclusion",
]

# Module-level LLMs; injected at startup via configure().
_primary_llm = None
_sub_llm = None


def configure(primary_llm, subllm=None) -> None:
    global _primary_llm, _sub_llm
    _primary_llm = primary_llm
    _sub_llm = subllm


class ReportWriterInput(StrictToolInput):
    analysis_json: str = Field(
        description="JSON string of the QuantAnalyst output to convert into a report"
    )
    tickers: list[str] = Field(description="List of tickers analysed")
    data_gaps: list[str] = Field(
        default_factory=list,
        description="List of data gaps identified during research",
    )


@tool("report_writer", args_schema=ReportWriterInput)
def report_writer_tool(
    analysis_json: str, tickers: list[str], data_gaps: list[str]
) -> str:
    """Assemble the final Markdown report from quantitative analysis JSON.

    Uses two LLM calls (Flash-Lite for structural sections, Flash for analytical).
    Validates mandatory sections and appends the disclaimer footer.
    """
    def _run():
        if _primary_llm is None:
            raise RuntimeError(
                "ReportWriterTool not configured — call report_writer.configure(llm)"
            )

        structural_llm = _sub_llm if _sub_llm is not None else _primary_llm

        # Call 1: structural sections (cheap)
        structural_response = structural_llm.invoke([
            SystemMessage(content=_STRUCTURAL_SYSTEM),
            HumanMessage(content=f"Analysis JSON:\n\n{analysis_json}"),
        ])
        structural_raw = structural_response.content if hasattr(structural_response, "content") else structural_response
        structural_part = content_to_str(structural_raw).strip()

        # Call 2: analytical sections (full reasoning)
        analytical_response = _primary_llm.invoke([
            SystemMessage(content=_ANALYTICAL_SYSTEM),
            HumanMessage(content=f"Analysis JSON:\n\n{analysis_json}"),
        ])
        analytical_raw = analytical_response.content if hasattr(analytical_response, "content") else analytical_response
        analytical_part = content_to_str(analytical_raw).strip()

        report = structural_part + "\n\n" + analytical_part
        report = _validate_sections(report)
        return _enforce_disclaimer(report)

    return safe_tool_call(
        "report_writer",
        _run,
        {"analysis_json": analysis_json[:200], "tickers": tickers},
    )


_DISCLAIMER = (
    "\n\n---\n"
    "*DISCLAIMER: This report was generated by an AI system. "
    "All figures should be independently verified before making any investment "
    "decisions. This is not financial advice.*"
)


def _validate_sections(report: str) -> str:
    """Ensure all mandatory section headings are present; add stubs for missing ones."""
    for section in _REQUIRED_SECTIONS:
        if f"## {section}" not in report and f"# {section}" not in report:
            logger.warning("Report missing mandatory section: %s — appending stub", section)
            report += f"\n\n## {section}\n*(Section could not be generated)*\n"
    return report


def _enforce_disclaimer(report: str) -> str:
    """Guarantee the disclaimer footer is present regardless of LLM output."""
    if "This is not financial advice" not in report:
        return report + _DISCLAIMER
    return report
