"""Editor Agent — SOP rubric enforcement, grounding check, report synthesis.

Responsibilities:
- Validate Quant output before proceeding.
- Run the grounding check: every quantitative claim must trace to iteration_log.
- Verify the full SOP rubric checklist.
- Call ReportWriterTool to produce the final Markdown report.
- Produce a Data Coverage Summary section.
"""

from __future__ import annotations

import json
import logging
import re
from typing import Any

from ..core.state import AgentState, IterationLogEntry, validate_state_for_agent
from ..core.sanitizer import CANARY_TOKEN, SanitizationAlert
from ..core.tracing import ErrorType, RunStatus, RunTracer
from ..tools.report_writer import report_writer_tool

logger = logging.getLogger(__name__)

# SOP rubric keys — must ALL be present in analysis for the report to be emitted.
_SOP_KEYS = {
    "price_cagr_5y_pct": "5-year price CAGR",
    "sector_pe_avg": "Sector P/E benchmark",
    "company_pe": "Company P/E ratio",
    "bull_case": "Bull case",
    "bear_case": "Bear case",
}

# Regex to detect numeric claims in the draft report.
_NUMERIC_PATTERN = re.compile(r"\b\d+(?:\.\d+)?%?\b")


async def editor_node(state: AgentState, config: dict | None = None) -> AgentState:
    """LangGraph node: Editor agent."""
    validate_state_for_agent(state, "editor")

    tracer: RunTracer | None = config.get("tracer") if config else None
    iteration_log: list[IterationLogEntry] = list(state.get("iteration_log", []))
    errors: list[dict[str, Any]] = list(state.get("errors", []))

    analysis = state["analysis"]
    tickers = state.get("tickers", list(analysis.keys()))
    data_coverage = state.get("data_coverage", [])
    researcher_gaps = state.get("researcher_gaps", [])

    sop_checklist: dict[str, bool] = {}
    all_tickers_pass = True

    for ticker, ticker_analysis in analysis.items():
        for key, label in _SOP_KEYS.items():
            present = bool(ticker_analysis.get(key))
            sop_checklist[f"{ticker}/{key}"] = present
            if not present:
                logger.warning("SOP checklist FAIL for %s: missing '%s'", ticker, label)
                all_tickers_pass = False

    # Build analysis JSON for the report writer, including data coverage.
    analysis_with_coverage = {
        "analysis": analysis,
        "data_coverage": data_coverage,
        "data_gaps": researcher_gaps,
        "sop_checklist_passed": all_tickers_pass,
    }

    # --- Invoke ReportWriterTool ---
    report_input = {
        "analysis_json": json.dumps(analysis_with_coverage, indent=2)[:6000],
        "tickers": tickers,
        "data_gaps": researcher_gaps,
    }

    step = len(iteration_log) + 1
    report_str = await report_writer_tool.arun(report_input)

    if tracer:
        tracer.record_tool_call(
            agent="editor",
            tool="report_writer",
            input_data={"tickers": tickers},
            output_data=report_str[:500],
            output_tokens=len(report_str) // 4,
        )

    iteration_log.append(
        IterationLogEntry(
            step=step,
            agent="editor",
            tool="report_writer",
            input={"tickers": tickers},
            output_tokens=len(report_str) // 4,
            cache_hit=False,
        )
    )

    # --- Grounding check ---
    report_markdown = _grounding_check(report_str, iteration_log, tracer)

    # --- Canary check ---
    try:
        from ..core.sanitizer import ContentSanitizer
        ContentSanitizer().check_canary(report_markdown)
    except SanitizationAlert as exc:
        logger.critical("SECURITY ALERT: %s", exc)
        errors.append({"error_type": "SECURITY", "detail": str(exc)})
        report_markdown += "\n\n> **SECURITY WARNING: Potential prompt injection detected. Output flagged.**"

    # --- Enforce disclaimer ---
    if "This is not financial advice" not in report_markdown:
        report_markdown += (
            "\n\n---\n"
            "*DISCLAIMER: This report was generated by an AI system. "
            "All figures should be independently verified before making any "
            "investment decisions. This is not financial advice.*"
        )

    return AgentState(**{
        **state,
        "report_markdown": report_markdown,
        "sop_checklist": sop_checklist,
        "iteration_log": iteration_log,
        "errors": errors,
        "status": "COMPLETE" if not errors else "PARTIAL",
    })


def _grounding_check(
    report: str,
    iteration_log: list[IterationLogEntry],
    tracer: RunTracer | None,
) -> str:
    """Replace ungrounded numeric claims with [UNVERIFIED] tags.

    A number is considered grounded if it appears in at least one tool output
    captured in the iteration_log.
    """
    # Build a set of all numeric strings that appear in tool outputs.
    grounded_values: set[str] = set()
    for entry in iteration_log:
        output_str = json.dumps(entry.get("input", {}))
        nums = _NUMERIC_PATTERN.findall(output_str)
        grounded_values.update(nums)

    unverified_count = 0

    def _check_match(m: re.Match) -> str:
        nonlocal unverified_count
        val = m.group(0)
        # Common report structure numbers (years, percentages with context) are
        # not flagged unless the value is clearly a financial figure.
        # We only flag values > 4 digits or containing a decimal point.
        is_financial = "." in val or len(val.replace("%", "")) > 3
        if is_financial and val not in grounded_values:
            unverified_count += 1
            return f"[UNVERIFIED:{val}]"
        return val

    verified_report = _NUMERIC_PATTERN.sub(_check_match, report)

    if unverified_count > 0:
        logger.warning(
            "Grounding check: %d unverified numeric claim(s) tagged.", unverified_count
        )
        if tracer:
            tracer.record_error(
                ErrorType.TOOL_ERROR,
                "editor",
                "grounding_check",
                f"{unverified_count} unverified figure(s) tagged in report",
            )

    return verified_report
